docRoot                   $VH_ROOT/html/
vhDomain                  $VH_NAME
enableGzip                1
enableIpGeo               1

index  {
  useServer               0
  indexFiles              index.php
}

scripthandler  {
  add                     lsapi:lsphp83 php
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
}

context / {
  location                $DOC_ROOT/
  allowBrowse             1
  phpIniOverride  {
    php_value upload_max_filesize  64M
    php_value post_max_size        64M
    php_value memory_limit         256M
    php_value max_execution_time   300
  }
}
