[variables]
main_domain = "${domain}"
db_name = "wordpress"
db_user = "wordpress"
db_password = "${password:32}"
db_root_password = "${password:32}"

[config]
env = [
  "WP_HOME=https://${main_domain}",
  "DB_HOST=wp-db",
  "DB_NAME=${db_name}",
  "DB_USER=${db_user}",
  "DB_PASSWORD=${db_password}",
  "DB_ROOT_PASSWORD=${db_root_password}"
]

[[config.domains]]
serviceName = "wordpress"
port = 80
host = "${main_domain}"

[[config.mounts]]
name = "wp_data"
mountPath = "/var/www/vhosts/localhost/html"

[[config.mounts]]
name = "ols_logs"
mountPath = "/usr/local/lsws/logs"

[[config.mounts]]
name = "db_data"
mountPath = "/var/lib/mysql"
